language: python

install:
   - pip install .
   - pip install coverage
   - pip install coveralls
   - pip install pyyaml

script: 
  - coverage run -m unittest discover
  
after_success:
  - coveralls